### ISSUE TITLE
Update How to contribute section

### ISSUE THREAD

**Issue by lauportell** [elixir-europe/rdmkit#1182]
- Explain where to get page_id
- Give more clear example for first way to make lists
- Is it clear what the contributors should read in this page?

**Comment by bedroesb** [comment]
> Explain where to get page_id

This is explained in the metadata of the template: `# More information on which page id you can use can be found at https://rdmkit.elixir-europe.org/website_overview`
> Give more clear example for first way to make lists

  This is exmplained in the markdown cheat sheet, which is linked to from contribute. 
> Is it clear what the contributors should read in this page?

  Not super clear to me what this means, we link to most relevant pages I think ...

**Comment by bedroesb** [comment]
Should we link to documentation in the metadata of all pages? Now we currently only do it in the template files. 

```yaml
title: Global problem title (e.g. metadata management)
search_exclude: true
description: <!---REPLACE THIS with a one sentence description of the page--->
contributors: [<!---REPLACE THIS with comma separated list of contributors--->]
page_id: <!---REPLACE THIS with a shortened page name. The shortened page name should be in lowercase and separated by underscore(s) if needed. For example, page_id of structural bioinformatics will be struct_bioinfo --->
related_pages: 
  tool_assembly: [<!---REPLACE THIS with the page ID of the tool_assembly pages that you want to list here as related pages--->]
# More information on which page id you can use can be found at https://rdmkit.elixir-europe.org/website_overview
training:
  - name:
    registry:
    url:
# More information on how to fill in this metadata section can be found here https://rdmkit.elixir-europe.org/page_metadata
```
