### ISSUE TITLE
Ideas for new topics

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1362]
Based on some tools we had without context we might want to create new sections/pages to give them a place in the RDMkit.
```yml
- description: An assembly of molecular interaction diagrams, established based on literature evidence
  name: COVID-19 Disease Map
  url: https://fairdomhub.org/projects/190
- description: Comparative analysis, data mining and visualisation for the genomes of non-vertebrate species
  name: Ensembl Genomes
  registry:
    biotools: ensembl_genomes
    fairsharing: 923a0p
    tess: Ensembl Genomes
  url: https://ensemblgenomes.org/
- description: MINT, the Molecular INTeraction database, focuses on experimentally verified protein-protein interactions mined from the scientific literature by expert curators
  name: MINT
  registry:
    biotools: mint
    fairsharing: 2bdvmk
  url: https://mint.bio.uniroma2.it/
- description: The Orphadata platform provides the scientific community with comprehensive, high-quality datasets related to rare diseases and orphan drugs, in a reusable and computable format
  name: Orphadata
  registry:
    biotools: orphadata
    fairsharing: d1a667
    fairsharing-coll: bsg-d001249
  url: http://www.orphadata.org/cgi-bin/index.php
- description: SILVA provides comprehensive, quality checked and regularly updated datasets of aligned small (16S/18S, SSU) and large subunit (23S/28S, LSU) ribosomal RNA (rRNA) sequences for all three domains of life (Bacteria, Archaea and Eukarya).
  name: Silva
  registry:
    biotools: silva
    fairsharing: 5vtYGG
    tess: Silva
  url: https://www.arb-silva.de/
  ```
  
Topics not covered in previous contentathon:
  
- [ ] FAIR software by design: documentation, versioning, licence, sharing&publishing, citing
- [x] How to apply ontologies in practice in every day work: tools, tips and tricks
- [ ] #1546
- [ ] #1547
- [ ] #1548
- [ ] #1549
